require "yak.options"
require "yak.keymaps"
require "yak.plugins"
-- require "yak.colo"
require "yak.yaknotes"
require "yak.cmp"
require "yak.lsp"
require "yak.telescope"
require "yak.treesitter"
require "yak.colorizer"
require "yak.autopairs"
require "yak.comment"
require "yak.gitsigns"
require "yak.nvim-tree"
require "yak.toggleterm"
require "yak.dap"
require "yak.lualine"
require "yak.neorg"

-- test comment
